### ISSUE TITLE
papertrailapp.com setup scripts

### ISSUE THREAD

**Issue by marsz** [5fpro/saturn#17]
memo

```
apt-get update
apt-get upgrade

wget https://github.com/papertrail/remote_syslog2/releases/download/v0.20-beta2/remote_syslog_linux_amd64.tar.gz
tar -xvf remote_syslog_linux_amd64.tar.gz
cp remote_syslog/remote_syslog /usr/local/bin
vim /etc/log_files.yml
remote_syslog
vim /etc/rc.local

vim /etc/rsyslog.d/95-papertrail.conf
service rsyslog restart
```

## 95-papertrail.conf

```
*.*    @logs6.papertrailapp.com:31397
```

## log_files.yml

```
files:
  - /home/apps/ifuntuan/shared/log/*.log
destination:
  host: logs6.papertrailapp.com
  port: 31397
  protocol: tls
pid_file: /var/run/remote_syslog.pid
```
